version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_laravel
      - MARIADB_DATABASE=bitnami_laravel
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306' # Opsiyonel: MariaDB'ye harici erişim için. Güvenlik nedeniyle yalnızca geliştirme ortamlarında kullanılmalıdır.

  myapp:
    image: 'bitnami/laravel:latest'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bitnami_laravel
      - DB_USERNAME=bn_laravel
      - DB_PASSWORD=password
    ports:
      - '80:3000'
    depends_on:
      - mariadb
    volumes:
      - '.:/app'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=bn_laravel
      - PMA_PASSWORD=password
    ports:
      - '8080:80'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
