version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_laravel
      - MARIADB_DATABASE=bitnami_laravel
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  myapp:
    image: 'bitnami/laravel:latest'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bitnami_laravel
      - DB_USERNAME=bn_laravel
      - DB_PASSWORD=password
    ports:
      - '80:3000'
    depends_on:
      - mariadb
    volumes:
      - '.:/app'
      
volumes:
  mariadb_data:
    driver: local
